/* Generated By:JavaCC: Do not edit this line. CedilhaConstants.java */
package Principal;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CedilhaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int FIMIF = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int FIMWHILE = 17;
  /** RegularExpression Id. */
  int INICIOPROG = 18;
  /** RegularExpression Id. */
  int FIMPROG = 19;
  /** RegularExpression Id. */
  int INTEIRO = 20;
  /** RegularExpression Id. */
  int PALAVRA = 21;
  /** RegularExpression Id. */
  int MOSTRA = 22;
  /** RegularExpression Id. */
  int ENTRADA = 23;
  /** RegularExpression Id. */
  int ATRIB = 24;
  /** RegularExpression Id. */
  int CONCAT = 25;
  /** RegularExpression Id. */
  int FIMLINHA = 26;
  /** RegularExpression Id. */
  int PARENTESQ = 27;
  /** RegularExpression Id. */
  int PARENTDIR = 28;
  /** RegularExpression Id. */
  int VARIAVEIS = 29;
  /** RegularExpression Id. */
  int NUMEROS = 30;
  /** RegularExpression Id. */
  int PALAVRAS = 31;
  /** RegularExpression Id. */
  int MAIS = 32;
  /** RegularExpression Id. */
  int MENOS = 33;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 34;
  /** RegularExpression Id. */
  int DIVISAO = 35;
  /** RegularExpression Id. */
  int POTENCIA = 36;
  /** RegularExpression Id. */
  int MAIOR = 37;
  /** RegularExpression Id. */
  int MENOR = 38;
  /** RegularExpression Id. */
  int MAIORIGUAL = 39;
  /** RegularExpression Id. */
  int MENORIGUAL = 40;
  /** RegularExpression Id. */
  int IGUAL = 41;
  /** RegularExpression Id. */
  int DIFERENTE = 42;
  /** RegularExpression Id. */
  int E = 43;
  /** RegularExpression Id. */
  int OU = 44;
  /** RegularExpression Id. */
  int NAO = 45;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int BLOCO_COMENTARIO = 1;
  /** Lexical state. */
  int LINHA_COMENTARIO = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"_\"",
    "\",\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 10>",
    "\"\\n\"",
    "<token of kind 12>",
    "\"SeNaoForIsso\"",
    "\"EhIsso\"",
    "\"FimDisso\"",
    "\"RodeAteQue\"",
    "\"Volta\"",
    "\"Inicia\"",
    "\"Termina\"",
    "\"Inteiro\"",
    "\"Palavra\"",
    "\"Mostra\"",
    "\"Entrada\"",
    "\"=\"",
    "\".\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<VARIAVEIS>",
    "<NUMEROS>",
    "<PALAVRAS>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\">\"",
    "\"<\"",
    "\"=>\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"&\"",
    "\"||\"",
    "\"!\"",
  };

}
