/* Generated By:JavaCC: Do not edit this line. CedilhaConstants.java */
package Principal;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CedilhaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 8;
  /** RegularExpression Id. */
  int IDENT = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int VOGAIS = 11;
  /** RegularExpression Id. */
  int ARQ = 12;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int comentario = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"break\"",
    "<IDENT>",
    "<INT>",
    "<VOGAIS>",
    "<ARQ>",
  };

}
